export type ExerciseInfo = { name: string; link: { type: "video"; url: string; source?: string }; cues: string[]; isTimed?: boolean; defaultSeconds?: number; };

export const EXERCISE_LIBRARY: Record<string, ExerciseInfo> = {
  "Kneeling Push-Ups": { name: "Kneeling Push-Ups", link: { type: "video", url: "https://www.youtube.com/watch?v=utzhPQuXWcA", source: "YouTube" }, cues: ["Straight line from head to knees, don't let hips sag or pike up", "Hands roughly under shoulders, elbows track back at about 45°", "Lower until chest nears the floor, full range beats fast partial reps"] },
  "Reverse Lunges (bodyweight)": { name: "Reverse Lunges (bodyweight)", link: { type: "video", url: "https://www.youtube.com/watch?v=u_zSfK5ZFU4", source: "BuiltLean" }, cues: ["Step back far enough that both knees can hit ~90°", "Front knee tracks over the ankle, not past the toes", "Torso stays upright, don't lean forward into the step"] },
  "Leg Raises (floor)": { name: "Leg Raises (floor)", link: { type: "video", url: "https://www.youtube.com/watch?v=xJJu-WiROM8", source: "YouTube" }, cues: ["Press lower back into the floor, don't let it arch as legs lower", "Move slow and controlled, momentum means the core stopped working", "Stop the descent at the point you can still keep your back flat"] },
  "Doorway Isometric Pulls": { name: "Doorway Isometric Pulls", link: { type: "video", url: "https://www.youtube.com/watch?v=lfPrQ8jahkM", source: "Dr. Dan / Turack Chiropractic" }, cues: ["Grip a door frame, lean back with straight arms, squeeze shoulder blades together", "Hold the pull, this is an isometric, there's no rep to rush through", "Keep a soft bend in the knees and a neutral spine, don't hyperextend the low back"], isTimed: true, defaultSeconds: 20 },
  "Chair Dips": { name: "Chair Dips", link: { type: "video", url: "https://www.youtube.com/watch?v=AWz_7B1cch0", source: "YouTube" }, cues: ["Use a sturdy, non-rolling chair, test it before loading it fully", "Elbows track backward, not flared out to the sides", "Lower only as far as your shoulders stay comfortable, stop if you feel pinching"] },
  "Bicep Curls (backpack)": { name: "Bicep Curls (backpack)", link: { type: "video", url: "https://www.youtube.com/watch?v=XE_pHwbst04", source: "Fit Father Project" }, cues: ["Elbows stay pinned at your sides through the whole rep", "Control the lowering phase, don't let the pack drop", "Pack ~10-20% of bodyweight to start, add books to adjust"] },
  "Glute Bridges (bodyweight)": { name: "Glute Bridges (bodyweight)", link: { type: "video", url: "https://www.youtube.com/watch?v=PuMKfB5a3jg", source: "YouTube" }, cues: ["Squeeze glutes to lift, don't push the low back into an arch to get height", "Drive through the heels, not the toes", "Brace the core before you lift to protect the lower back"] },
  "Plank (20-30 sec)": { name: "Plank", link: { type: "video", url: "https://www.youtube.com/watch?v=mwlp75MS6Rg", source: "NASM" }, cues: ["Straight line from shoulders to heels, squeeze glutes and brace the core", "Don't let hips sag or pike up as fatigue sets in", "Neck neutral, eyes toward the floor, not straining to look forward"], isTimed: true, defaultSeconds: 30 },
  "Banded Bent-Over Rows": { name: "Banded Bent-Over Rows", link: { type: "video", url: "https://www.youtube.com/watch?v=tcMmJ3c5P8c", source: "YouTube" }, cues: ["Hinge at the hips, flat back, not rounded", "Pull elbows back and up, squeeze shoulder blades at the top", "Keep a soft bend in the knees throughout"] },
  "Bodyweight Squats": { name: "Bodyweight Squats", link: { type: "video", url: "https://www.youtube.com/watch?v=DlS-GAF8Edg", source: "YouTube" }, cues: ["Knees track over toes, don't let them cave inward", "Weight in the heels and midfoot, chest stays tall", "Go as low as mobility allows with control, depth over speed"] },
  "Incline Push-Ups": { name: "Incline Push-Ups", link: { type: "video", url: "https://www.youtube.com/watch?v=0JUrOH--Kdk", source: "NASM" }, cues: ["Hands on a stable, non-sliding surface, counter or sturdy couch arm", "Same straight body line as a standard push-up, just at an angle", "Lower the incline as you get stronger to keep progressing"] },
  "Step-Ups (chair)": { name: "Step-Ups (chair)", link: { type: "video", url: "https://www.youtube.com/watch?v=WCFCdxzFBa4", source: "YouTube" }, cues: ["Use a step low and sturdy enough that your whole foot lands flat", "Drive through the stepping leg, don't push off the trailing foot", "Control the step down, don't just drop"] },
  Penguins: { name: "Penguins", link: { type: "video", url: "https://www.youtube.com/watch?v=_Dgy80CBfWg", source: "YouTube" }, cues: ["Lying or seated crunch position, reach one hand toward the same-side heel", "Keep the movement controlled, this is a small range-of-motion ab exercise", "Alternate sides evenly"] },
  Supermans: { name: "Supermans", link: { type: "video", url: "https://www.youtube.com/watch?v=BO1Xlqp5o90", source: "YouTube" }, cues: ["Lift chest and legs a few inches, this isn't about height, it's about control", "Keep the neck neutral, don't crank your head back to look up", "Hold briefly at the top, lower with control"] },
  "Dead Bugs": { name: "Dead Bugs", link: { type: "video", url: "https://www.youtube.com/watch?v=2aGunzN5YWA", source: "YouTube (McGill's Big 3 + Dead Bugs)" }, cues: ["Press lower back flat into the floor and keep it there the whole set", "Move opposite arm and leg slowly, stop before your back wants to arch", "Breathe, don't hold your breath through the rep"] },
  "Calf Raises (bodyweight)": { name: "Calf Raises (bodyweight)", link: { type: "video", url: "https://www.youtube.com/watch?v=2tvsvCRCQZY", source: "YouTube" }, cues: ["Full range, all the way up onto the toes, all the way back down", "Control the descent instead of dropping the heels", "Hold a wall or counter lightly for balance, not to take on weight"] },
  Crunches: { name: "Crunches", link: { type: "video", url: "https://www.youtube.com/watch?v=GWIEON0VSaY", source: "YouTube" }, cues: ["Lift shoulder blades off the floor, don't yank on the neck with your hands", "Exhale on the way up, keep the lower back in contact with the floor", "Small controlled range beats a big swinging motion"] },
  "Backpack Bent-Over Rows": { name: "Backpack Bent-Over Rows", link: { type: "video", url: "https://www.youtube.com/watch?v=UL8ZcK64KxA", source: "Men's Health UK" }, cues: ["Hinge at the hips, flat back, same setup as a standard bent-over row", "Pull the pack toward your waist, elbows close to the body", "Load with books to adjust, add slowly"] },
  "Reverse Snow Angels": { name: "Reverse Snow Angels", link: { type: "video", url: "https://www.youtube.com/watch?v=Vib5MB05hF0", source: "YouTube" }, cues: ["Face down, arms sweep from hips to overhead, squeezing shoulder blades together", "Small range, this is about upper-back control, not big fast arm swings", "Keep the neck neutral, forehead can rest lightly on the floor"] },
  "Standard Push-Ups": { name: "Standard Push-Ups", link: { type: "video", url: "https://www.youtube.com/watch?v=IODxDxX7oi4", source: "YouTube" }, cues: ["Hands slightly wider than shoulders, straight line from head to heels", "Lower until your chest nearly touches the floor, elbows at about 45°", "Press through the whole hand, don't let the hips sag or pike"] },
  "Goblet Squats (Kettlebell)": { name: "Goblet Squats (Kettlebell)", link: { type: "video", url: "https://www.youtube.com/watch?v=aNDUbH_Uv4g", source: "Zack Henderson" }, cues: ["Hold the kettlebell close to your chest, elbows tucked in", "Sit the hips back and down, knees tracking over the toes", "Keep your chest tall through the bottom of the squat, drive through the heels to stand"] },
  "Russian Twists (Kettlebell)": { name: "Russian Twists (Kettlebell)", link: { type: "video", url: "https://www.youtube.com/watch?v=wkD8rjkodUI", source: "YouTube" }, cues: ["Lean back to about 45°, feet can stay grounded if balance is tough", "Rotate from your torso, not just your arms, tap the kettlebell down on each side", "Keep the movement controlled, this is about rotation, not speed"] },
  "Kettlebell Single-Arm Rows": { name: "Kettlebell Single-Arm Rows", link: { type: "video", url: "https://www.youtube.com/watch?v=l5qelXL5nfs", source: "YouTube" }, cues: ["Hinge at the hips with a flat back, staggered stance for stability", "Row the kettlebell to your hip, elbow tracking close to your body", "Control the lowering phase, don't let the weight drop"] },
  "Bulgarian Split Squats (Chair)": { name: "Bulgarian Split Squats (Chair)", link: { type: "video", url: "https://www.youtube.com/watch?v=2C-uNgKwPLE", source: "YouTube" }, cues: ["Rear foot up on a sturdy chair, front foot far enough forward for a 90° front knee", "Lower straight down, front knee tracks over the ankle, not past the toes", "Keep most of your weight in the front leg, use the back leg for balance only"] },
  "Kettlebell Swings": { name: "Kettlebell Swings", link: { type: "video", url: "https://www.youtube.com/watch?v=YSxHifyI6s8", source: "YouTube" }, cues: ["This is a hip hinge, not a squat, the power comes from snapping the hips forward", "Let the kettlebell float up to chest height, don't lift it with your arms", "Keep a flat back throughout, brace your core hard at the top of each rep"] },
};

export function lookupExercise(name: string): ExerciseInfo | undefined { return EXERCISE_LIBRARY[name]; }
export function getYouTubeEmbedId(watchUrl: string): string { const match = watchUrl.match(/[?&]v=([^&]+)/); return match ? match[1] : ""; }
